In [1]:
import pandas as pd

df = pd.DataFrame({
    "Type" : ["SSD", "SSD", "HDD", "HDD", "SSD", "Flash", "Flash", "SSD", "SD"]
})
df

    Type
0    SSD
1    SSD
2    HDD
3    HDD
4    SSD
5  Flash
6  Flash
7    SSD
8     SD

In [ ]:
# OneHotEncoding using pandas
pd.get_dummies(df)

   Type_Flash  Type_HDD  Type_SD  Type_SSD
0       False     False    False      True
1       False     False    False      True
2       False      True    False     False
3       False      True    False     False
4       False     False    False      True
5        True     False    False     False
6        True     False    False     False
7       False     False    False      True
8       False     False     True     False

In [ ]:
pd.get_dummies(df, drop_first=True) # Avoid Dummy Problem for Linear regression

   Type_HDD  Type_SD  Type_SSD
0     False    False      True
1     False    False      True
2      True    False     False
3      True    False     False
4     False    False      True
5     False    False     False
6     False    False     False
7     False    False      True
8     False     True     False